version: '3.8'

services:
  todo-app:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - todo-db
    environment:
      - DATABASE_HOST=todo-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Password123!
      - DATABASE_DB=todo

  todo-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
